### ISSUE TITLE
log enhancement for soul-bootstrap & soul-admin

### ISSUE THREAD

**Issue by MarcusJiang1306** [dromara/soul#1002]
## Task

I found when rate-limiter open and connect to redis won't print log in console and I think make user confuse
Update dashboard data also won't print log
And AbstractSoulPlugin ruleLog will print ```selector success match``` but it should print rule success match.

Task List:

- [ ] Print log for connect to redis 
- [x] Print log for when dashboard data updated
- [x] replance ruleLog to rule success  @zhaozhengping

Please read the [Contribution Guideline](https://dromara.org/website/en-us/docs/soul/contributor.html) before submitting the PR

**Comment by zhaozhengping** [comment]
please assign to me. it is my first time to participate in soul project. please let me try. thanks.

**Comment by yu199195** [comment]
@zhaozhengping which task ？

**Comment by zhaozhengping** [comment]
i want try the 3 tasks all. but i has some question about the second one.  dashboard data is about DashboardUserController of soule-admin?

**Comment by zhaozhengping** [comment]
i forked soul ,found "soul-dashboard" module is empty.

**Comment by zhaozhengping** [comment]
> I found when rate-limiter open and connect to redis won't print log in console and I think make user confuse
> Print log for connect to redis

Is this RedisRateLimiter in soule-plugin-ratelimiter module,not in soul-bootstrap & soul-admin?

**Comment by MarcusJiang1306** [comment]
In exsiting logic when user submit Redis info to admin it won't connect to Redis, the first time connection to Redis is when there have a request in coming if need use Redis. but rate_limiter plugin will catched exception and there will be no recoreds on the log
