### ISSUE TITLE
add data access for soul-admin

### ISSUE THREAD

**Issue by nuo-promise** [dromara/soul#1255]
## Task
discuss data permission configuration scheme；
data permission configuration page;

Task List:

- [x] discuss data permission configuration scheme @fengzhenbing 
- [x] data permission configuration page @fengzhenbing @plutokaito 
- [x] store user id and userName after soul-admin logon (optimized) @nuo-promise 
- [x] The user information associated with the data permission. If the data information is changed, the data in the data permission table must be synchronized. @nuo-promise @plutokaito 

Please read the [Contribution Guideline](https://dromara.org/projects/soul/contributor/) before submitting the PR

**Comment by plutokaito** [comment]
get

**Comment by yu199195** [comment]
please add design scheme~

**Comment by nuo-promise** [comment]
> please add design scheme~

ok, writing now!

**Comment by nuo-promise** [comment]
### scene
To implement the differences between the agent and the plugin **selector** / **rule** By different business sector management, need to plugin **selector** / **rule** control data security
### target

- The user does not have the data permission. By default, all data can be operated.
   - As long as you set data permissions, you can only see the bound data.
- The user information associated with the data permission. If the data information is changed, the data in the data permission table must be synchronized.
   - User information changes
   - Change the selector data corresponding to the plugin
   - Change the rule data corresponding to the plugin
### table structure
![data_permission.png](https://cdn.nlark.com/yuque/0/2021/png/2312798/1618476628788-3a6ce37d-03c1-4e7e-99af-3f3b071d5c04.png#align=left&display=inline&height=454&margin=%5Bobject%20Object%5D&name=data_permission.png&originHeight=1914&originWidth=2790&size=153099&status=done&style=shadow&width=662)
**data_permission** 

| field| type | description |
| --- | --- | --- |
| id | varchar | primary key id varchar |
| user_id | varchar | user id |
| data_id | varchar  | selector id, rule id |
| data_type | int | 0:selector 1:rule |

###  feature list

1. Store user id and userName after soul-admin logon (optimized)
2. soul-admin adds user and data Association operations with soul-dashboardOn the user management page Data permission configuration Button)
   - List all plugins, corresponding selector, and rule data.
   - Bind and unbind plug-in data from user id
3. The user information associated with the data permission. If the data information is changed, the data in the data permission table must be synchronized.

**Comment by nuo-promise** [comment]
> get

add method
1. deleteByUserId(final String userId)
2. deleteByDataId(final String dataId)
